# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6caf6f3e6dc427c2bfec0cd90ecaaaa87eeb04a49baf0736574f57f4eb8021986935aa02adbe3d6ed37fea649e299a56e4fd81800d8dbe57da5ac520fd355d8

test:
  secret_key_base: 092220b83e41b67854b3bc529de28c518e80971919bb3156bea81556ecef17cc0c411895d79eed74bcda5eda37eb04af1a43ad1c1e838840e6327f0e474b7601

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
